@HOST = http://localhost:5200
GET {{HOST}}/musics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MDFiMjRjMy05OWRjLTRkMDAtYTg0Ni04NWQ4NWY3ZDFhZjEiLCJnaXZlbl9uYW1lIjoiTW9oYW1tYWQgcmV6YSIsImZhbWlseV9uYW1lIjoiYWhtYWRpIiwianRpIjoiZGM4OGYxMTEtZTU5Yy00MDM0LTg0MTEtM2JmNTU4N2IxZmYxIiwiZXhwIjoxNjk5MDUwMzkwLCJpc3MiOiJTdHJhd011c2ljIiwiYXVkIjoiU3RyYXdNdXNpYyJ9.9osocZL1Qco2jBhBitm33M_NCMwZ6QlAdL8qm9yzxhs