@HOST = http://localhost:5200
GET {{HOST}}/musics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMzIwMzA1My02NzNkLTQ3ZjQtODczOS0zNTZhMTE0ZTIxYjciLCJnaXZlbl9uYW1lIjoiTW9oYW1tYWQgcmV6YSIsImZhbWlseV9uYW1lIjoiYWhtYWRpIiwianRpIjoiODVmNTEzNzYtMzgyNS00M2Q5LTg5ODktNTAzNWNkYmEzNTRiIiwiZXhwIjoxNjk4MDA3NTM5LCJpc3MiOiJIZWxpb3MiLCJhdWQiOiJIZWxpb3MifQ.6giFcIcY-_zKB--a-U4YVf_RoY2d39EBt2MIH8JCmCk