@HOST = http://localhost:5200
GET {{HOST}}/musics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNGQzNjZhNy1kNjlkLTQyMGUtOWY4Ny0zODJmNjc0YzRkNzMiLCJnaXZlbl9uYW1lIjoiTW9oYW1tYWQgcmV6YSIsImZhbWlseV9uYW1lIjoiYWhtYWRpIiwianRpIjoiMjkwNzZiOGEtZGNkYi00MjUzLWFhNmYtOTE4YzNmOTdiY2VkIiwiZXhwIjoxNjk2NjAzMjIzLCJpc3MiOiJIZWxpb3MiLCJhdWQiOiJIZWxpb3MifQ.WCqfasW-FQhUh33ae0TIkDodXVDxtfaHYXN7Q0Ba9D0