@HOST = http://localhost:5200
GET {{HOST}}/musics/music/1
Authorization:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYzAxZjc4YS1hNmRlLTQ4NDYtYmQ0ZC0wNmFkNDQ4NDhlNjQiLCJnaXZlbl9uYW1lIjoiTW9oYW1tYWQgcmV6YSIsImZhbWlseV9uYW1lIjoiYWhtYWRpIiwianRpIjoiMTMwMTc2NTktYjVkNy00N2UxLWFmYzYtODU1ZjZlNTFhODBiIiwiZXhwIjoxNjk5MDI1OTI4LCJpc3MiOiJTdHJhd011c2ljIiwiYXVkIjoiU3RyYXdNdXNpYyJ9.1Wo6GpaIAvdHXIWkyK-FaZOpWeUy-Nm11poVidJD-c8"