@HOST = http://localhost:5200
GET {{HOST}}/musics/getmusicbyid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZDk2NTNhYS0yMWJiLTQ1ZmUtYmFhYy1jOGU2MjZjN2Y1YjUiLCJnaXZlbl9uYW1lIjoiTW9oYW1tYWQgcmV6YSIsImZhbWlseV9uYW1lIjoiYWhtYWRpIiwianRpIjoiY2Q4YjY5OGUtOTIwZC00OTc0LWFkYzAtMTViNjM2YjViYTBjIiwiZXhwIjoxNjk5MDUyMjk4LCJpc3MiOiJTdHJhd011c2ljIiwiYXVkIjoiU3RyYXdNdXNpYyJ9.yh3Y3v3TNMIHnAHoiYFQApQ1LjaNCPYADR7mAAAQmgk

{
    "id":"7c4aec15-223c-40a3-b0bb-641b6fb0d3a1"
}